entities:
  ippool:
    columns:
      - title: Name
        content: .metadata.name
      - title: Allocated
        content: .status.progress.allocatedAddresses
      - title: Linked
        content: .status.progress.linkedAddresses
      - title: Unlinked
        content: .status.progress.unlinkedAddresses
    primary: Name
api:
  List:
    content: Items
    entity: ippool
  Get:
    content: .
    entity: ippool
  Create:
    content: .
    entity: ippool
  Update:
    entity: ippool
aliases:
- entity: ippool
  use: list
  alias_to: List
  aliases:
  - ls
  help: List ippools
  alias_help: List
  command:
  - ippool
  - api
  - List
  - --output
  - table
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: ippool
  use: describe id
  alias_to: Get
  aliases:
  - desc
  help: Describe an ippool
  alias_help: Get id
  command:
  - ippool
  - api
  - Get
  - '%0'
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: ippool
  use: delete id [id]...
  help: Delete an ippool
  alias_to: Delete
  alias_help: Delete id
  aliases:
  - del
  - rm
  command:
  - ippool
  - api
  - Delete
  - '%0'
  - --output
  - success
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: ippool
  use: create
  help: Create an ippool
  alias_to: Create
  aliases:
  - add
  command:
  - ippool
  - api
  - Create
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
  - name: name
    alias_to: ObjectMeta.Name
    required: true
  - name: num-addresses
    alias_to: Spec.NumAddresses
    required: true
