entities:
  oosaccess:
    columns:
      - title: Name
        content: .metadata.name
      - title: Audit
        content: .spec.audit.readers
      - title: IaaS
        content: .spec.iaas.readers
    primary: Name
api:
  List:
    content: Items
    entity: oosaccess
  Get:
    content: .
    entity: oosaccess
  Create:
    content: .
    entity: oosaccess
  Update:
    entity: oosaccess
aliases:
- entity: oosaccess
  use: describe
  alias_to: Get
  aliases:
  - desc
  help: Describe the OOS access configuration
  alias_help: Get oks-oos-configuration
  command:
  - oosaccess
  - api
  - Get
  - oks-oos-configuration
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
