api:
  ListBuckets:
    content: Buckets
    entity: bucket
    group: Bucket
  HeadBucket:
    content: .
    entity: bucket
    group: Bucket
  ListObjectsV2:
    content: Contents
    entity: object
    group: Object
  ListObjectVersions:
    content: Versions
    entity: objectversion
    group: Object
  GetObject:
    content: .
    entity: objectmetadata
    group: Object
  HeadObject:
    content: .
    entity: objectmetadata
    group: Object
  GetBucketAcl:
    content: .
    entity: acl
    group: Bucket
  GetBucketCors:
    content: CORSRules
    entity: cors
    group: Bucket
  GetBucketEncryption:
    content: ServerSideEncryptionConfiguration
    entity: encryption
    group: Bucket
  GetBucketVersioning:
    entity: versioning
    group: Bucket
  GetBucketLocation:
    content: .
    entity: location
    group: Bucket
  GetBucketPolicy:
    content: Policy
    entity: policy
    group: Bucket
  GetBucketLifecycleConfiguration:
    content: .
    entity: lifecycle
    group: Bucket
  GetBucketWebsite:
    content: .
    entity: website
    group: Bucket
  PutBucketWebsite:
    content: .
    entity: website
    group: Bucket
  GetObjectAcl:
    content: .
    entity: acl
    group: Object
  GetObjectRetention:
    content: Retention
    entity: retention
    group: Object
  GetObjectLockConfiguration:
    content: ObjectLockConfiguration
    entity: lockconfiguration
    group: Object
  GetObjectTagging:
    content: .
    entity: tagging
    group: Object
entities:
  bucket:
    columns:
    - title: Name
      content: .Name
    primary: Bucket
  object:
    columns:
    - title: Key
      content: .Key
    - title: Size
      content: .Size
    - title: LastModified
      content: .LastModified
    primary: Key
aliases:
- entity: bucket
  use: describe bucket
  alias_to: HeadBucket
  aliases:
  - desc
  help: Display a bucket.
  alias_help: HeadBucket --Bucket bucket
  command:
  - api
  - HeadBucket
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: object
  use: describe key
  alias_to: HeadObject
  aliases:
  - desc
  help: Display an object metadata.
  alias_help: HeadObject --Key key
  command:
  - api
  - HeadObject
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  use: versions
  alias_to: ListObjectVersions
  aliases:
  - desc
  help: Display an object metadata.
  alias_help: ListObjectVersions
  command:
  - api
  - ListObjectVersions
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  use: download key
  alias_to: GetObject
  aliases:
  - down
  help: Download an object.
  alias_help: GetObject --Key key
  command:
  - api
  - GetObject
  - --Key
  - '%0'
  - --output
  - body
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
  - name: version
    alias_to: VersionId
  - name: part
    alias_to: PartNumber
  - name: range
    alias_to: Range
    help: Range to download, as defined by RFC 9110 (e.g. bytes=0-500)
- entity: object
  use: copy bucket_src/key_src key_dst
  alias_to: CopyObject
  aliases:
  - cp
  help: Copy an object.
  alias_help: CopyObject --CopySource bucket_src/key_src --Key key_dst
  command:
  - api
  - CopyObject
  - --CopySource
  - '%0'
  - --Key
  - '%1'
  - --output
  - success
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
  - name: expires
    alias_to: Expires
  - name: grant-full-control
    alias_to: GrantFullControl
  - name: grant-read
    alias_to: GrantRead
  - name: grant-read-acp
    alias_to: GrantReadACP
  - name: grant-write-acp
    alias_to: GrantWriteACP
  - name: tagging
    alias_to: Tagging
  - name: tagging-directive
    alias_to: TaggingDirective
  - name: cache-control
    alias_to: CacheControl
  - name: content-disposition
    alias_to: ContentDisposition
  - name: content-encoding
    alias_to: ContentEncoding
  - name: content-language
    alias_to: ContentLanguage
  - name: content-type
    alias_to: ContentType
  - name: server-side-encryption
    alias_to: ServerSideEncryption
  - name: object-lock-mode
    alias_to: ObjectLockMode
  - name: object-lock-retain-until-date
    alias_to: ObjectLockRetainUntilDate
  - name: website-redirect-location
    alias_to: WebsiteRedirectLocation
- entity: bucket
  sub_command: versioning
  use: describe bucket
  alias_to: GetBucketVersioning
  aliases:
  - desc
  help: Display versioning configuration.
  alias_help: GetBucketVersioning --Bucket bucket
  command:
  - api
  - GetBucketVersioning
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: versioning
  use: enable bucket
  alias_to: PutBucketVersioning
  help: Enable versioning.
  alias_help: PutBucketVersioning --Bucket bucket --VersioningConfiguration.Status Enabled
  command:
  - api
  - PutBucketVersioning
  - --Bucket
  - '%0'
  - --VersioningConfiguration.Status
  - Enabled
  - --output
  - success
- entity: bucket
  sub_command: versioning
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: PutBucketVersioning
  help: Disable versioning.
  alias_help: PutBucketVersioning --Bucket bucket --VersioningConfiguration.Status Suspended
  command:
  - api
  - PutBucketVersioning
  - --Bucket
  - '%0'
  - --VersioningConfiguration.Status
  - Suspended
  - --output
  - success
- entity: bucket
  sub_command: encryption
  use: describe bucket
  alias_to: GetBucketEncryption
  aliases:
  - desc
  help: Display encryption configuration.
  alias_help: GetBucketEncryption --Bucket bucket
  command:
  - api
  - GetBucketEncryption
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: encryption
  use: enable bucket
  alias_to: PutBucketEncryption
  help: Enable encryption.
  alias_help: PutBucketEncryption --Bucket bucket --ServerSideEncryptionConfiguration.Rules.0.ApplyServerSideEncryptionByDefault.SSEAlgorithm AES256
  command:
  - api
  - PutBucketEncryption
  - --Bucket
  - '%0'
  - --ServerSideEncryptionConfiguration.Rules.0.ApplyServerSideEncryptionByDefault.SSEAlgorithm
  - AES256
  - --output
  - success
- entity: bucket
  sub_command: encryption
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketEncryption
  help: Disable encryption.
  alias_help: DeleteBucketEncryption --Bucket bucket
  command:
  - api
  - DeleteBucketEncryption
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: acl
  use: describe bucket
  alias_to: GetBucketAcl
  aliases:
  - desc
  help: Display ACL configuration.
  alias_help: GetBucketAcl --Bucket bucket
  command:
  - api
  - GetBucketAcl
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: acl
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketAcl
  help: Update ACL configuration.
  alias_help: PutBucketAcl --Bucket bucket
  command:
  - api
  - PutBucketAcl
  - --Bucket
  - '%0'
  - --root
  - AccessControlPolicy
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the ACL config (JSON format, i.e. {"Grants":[...]})'
  - name: from-string
    alias_to: payload
    help: 'The ACL config (JSON format, i.e. {"Grants":[...]})'
  - name: acl
    alias_to: ACL
  - name: grant-full-control
    alias_to: GrantFullControl
  - name: grant-read
    alias_to: GrantRead
  - name: GrantReadACP
    alias_to: grant-read-acp
  - name: grant-write
    alias_to: GrantWrite
  - name: grant-write-acp
    alias_to: GrantWriteACP
- entity: bucket
  sub_command: cors
  use: describe bucket
  alias_to: GetBucketCors
  aliases:
  - desc
  help: Display CORS configuration.
  alias_help: GetBucketCors --Bucket bucket
  command:
  - api
  - GetBucketCors
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: cors
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketCors
  help: Update CORS configuration.
  alias_help: PutBucketCors --Bucket bucket
  command:
  - api
  - PutBucketCors
  - --Bucket
  - '%0'
  - --root
  - CORSConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the CORS config (JSON format, i.e. {"CORSRules":[...]})'
  - name: from-string
    alias_to: payload
    help: 'The CORS config (JSON format, i.e. {"CORSRules":[...]})'
- entity: bucket
  sub_command: cors
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketCors
  help: Delete CORS configuration.
  alias_help: DeleteBucketCors --Bucket bucket
  command:
  - api
  - DeleteBucketCors
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: lifecycle
  use: describe bucket
  alias_to: GetBucketLifecycleConfiguration
  aliases:
  - desc
  help: Display lifecycle configuration.
  alias_help: GetBucketLifecycleConfiguration --Bucket bucket
  command:
  - api
  - GetBucketLifecycleConfiguration
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: lifecycle
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketLifecycleConfiguration
  help: Update lifecycle configuration.
  alias_help: PutBucketLifecycleConfiguration --Bucket bucket
  command:
  - api
  - PutBucketLifecycleConfiguration
  - --Bucket
  - '%0'
  - --root
  - LifecycleConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the Lifecycle config (JSON format, i.e. {"Rules":[...]})'
  - name: from-string
    alias_to: payload
    help: 'The Lifecycle config (JSON format, i.e. {"Rules":[...]})'
- entity: bucket
  sub_command: lifecycle
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketLifecycle
  help: Delete lifecycle configuration.
  alias_help: DeleteBucketLifecycle --Bucket bucket
  command:
  - api
  - DeleteBucketLifecycle
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: objectlock
  use: describe bucket
  alias_to: GetObjectLockConfiguration
  aliases:
  - desc
  help: Delete ObjectLock configuration.
  alias_help: GetObjectLockConfiguration --Bucket bucket
  command:
  - api
  - GetObjectLockConfiguration
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: objectlock
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutObjectLockConfiguration
  help: Update ObjectLock configuration.
  alias_help: PutObjectLockConfiguration --Bucket bucket
  command:
  - api
  - PutObjectLockConfiguration
  - --Bucket
  - '%0'
  - --root
  - ObjectLockConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the ObjectLock config (JSON format, i.e. {"ObjectLockEnabled":"Enabled", "Rule":{...}})'
  - name: from-string
    alias_to: payload
    help: 'The ObjectLock config (JSON format, i.e. {"ObjectLockEnabled":"Enabled", "Rule":{...}})'
- entity: bucket
  sub_command: website
  use: describe bucket
  alias_to: GetBucketWebsite
  aliases:
  - desc
  help: Display website configuration.
  alias_help: GetBucketWebsite --Bucket bucket
  command:
  - api
  - GetBucketWebsite
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: website
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketWebsite
  help: Update website configuration.
  alias_help: PutBucketWebsite --Bucket bucket
  command:
  - api
  - PutBucketWebsite
  - --Bucket
  - '%0'
  - --root
  - WebsiteConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the website config (JSON format, e.g. {"ErrorDocument":{...},"IndexDocument":{...},"RoutingRules":[...]})'
  - name: from-string
    alias_to: payload
    help: 'The website config (JSON format, e.g. {"ErrorDocument":{...},"IndexDocument":{...},"RoutingRules":[...]})'
- entity: bucket
  sub_command: website
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketWebsite
  help: Delete website configuration.
  alias_help: DeleteBucketWebsite --Bucket bucket
  command:
  - api
  - DeleteBucketWebsite
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: policy
  use: describe bucket
  alias_to: GetBucketPolicy
  aliases:
  - desc
  help: Display Policy configuration.
  alias_help: GetBucketPolicy --Bucket bucket
  command:
  - api
  - GetBucketPolicy
  - --Bucket
  - '%0'
  - --output
  - text
- entity: bucket
  sub_command: policy
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketPolicy
  help: Update Policy configuration.
  alias_help: PutBucketPolicy --Bucket bucket
  command:
  - api
  - PutBucketPolicy
  - --Bucket
  - '%0'
  - --output
  - success
  flags:
  - name: from-file
    alias_to: Policy
    required: false
    help: 'The file storing the policy config (JSON format, i.e. {"Version":"...","Statement":[...]})'
  - name: from-string
    alias_to: Policy
    required: false
    help: 'The policy config (JSON format, i.e. {"Version":"...","Statement":[...]})'
  - name: remove-access
    alias_to: ConfirmRemoveSelfBucketAccess
- entity: bucket
  sub_command: policy
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketPolicy
  help: Delete Policy configuration.
  alias_help: DeleteBucketPolicy --Bucket bucket
  command:
  - api
  - DeleteBucketPolicy
  - --Bucket
  - '%0'
  - --output
  - success
- entity: object
  sub_command: acl
  use: describe key
  alias_to: GetObjectAcl
  aliases:
  - desc
  help: Display ACL configuration.
  alias_help: GetObjectAcl --Bucket bucket
  command:
  - api
  - GetObjectAcl
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: acl
  use: configure key
  alias_to: PutObjectAcl
  aliases:
  - config
  - cfg
  help: Configure ACL.
  alias_help: PutObjectAcl --Bucket bucket
  command:
  - api
  - PutObjectAcl
  - --Key
  - '%0'
  - --root
  - AccessControlPolicy
  - --output
  - yaml
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the ACL config (JSON format, i.e. {"Grants":[...]})'
  - name: from-string
    alias_to: payload
    help: 'The ACL config (JSON format, i.e. {"Grants":[...]})'
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: retention
  use: desc key
  alias_to: GetObjectRetention
  aliases:
  - desc
  help: Display object retention configuration.
  alias_help: GetObjectRetention --Key key
  command:
  - api
  - GetObjectRetention
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: retention
  use: configure key
  alias_to: PutObjectRetention
  aliases:
  - config
  - cfg
  help: Configure object retention.
  alias_help: PutObjectRetention --Key key --Retention.Mode COMPLIANCE
  command:
  - api
  - PutObjectRetention
  - --Key
  - '%0'
  - --Retention.Mode
  - COMPLIANCE
  - --output
  - success
  flags:
  - name: retain-until
    alias_to: Retention.RetainUntilDate
    required: true
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: tagging
  use: describe key
  alias_to: GetObjectTagging
  aliases:
  - desc
  help: List object tags.
  alias_help: GetObjectTagging --Key key
  command:
  - api
  - GetObjectTagging
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: tagging
  use: configure key
  aliases:
    - config
    - cfg
  alias_to: PutObjectTagging
  help: Add tags to an object.
  alias_help: PutObjectTagging --Key key
  command:
  - api
  - PutObjectTagging
  - --Key
  - '%0'
  - --root
  - Tagging
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    help: 'The file storing the tagging config (JSON format, i.e. {"TagSet":[{"Key":"...", "Value":"..."}]})'
  - name: from-string
    alias_to: payload
    help: 'The tagging config (JSON format, i.e. {"TagSet":[{"Key":"...", "Value":"..."}]})'
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: tagging
  use: delete key
  aliases:
    - del
    - rm
  alias_to: DeleteObjectTagging
  help: Delete all tags from an object.
  alias_help: DeleteObjectTagging --Key key
  command:
  - api
  - DeleteObjectTagging
  - --Key
  - '%0'
  - --output
  - success
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: bucket
  use: delete bucket [bucket]...
  alias_to: DeleteBucket
  aliases:
  - del
  - rm
  help: Delete a bucket.
  alias_help: DeleteBucket --Bucket bucket
  command:
  - api
  - DeleteBucket
  - --Bucket
  - '%0'
  - --output
  - success
  flags:
  - name: expected-bucket-owner
    alias_to: ExpectedBucketOwner
  prompt:
    action: delete
