api:
  Create:
    use: Create
    content: .
    entity: netpeering
    flags:
    - name: ObjectMeta.Name
      kind: 24
    - name: ObjectMeta.GenerateName
      kind: 24
    - name: ObjectMeta.Namespace
      kind: 24
    - name: ObjectMeta.SelfLink
      kind: 24
    - name: ObjectMeta.UID
      kind: 24
    - name: ObjectMeta.ResourceVersion
      kind: 24
    - name: ObjectMeta.DeletionTimestamp
      kind: 24
      customValue: fileOrJson
    - name: ObjectMeta.DeletionGracePeriodSeconds
      kind: 6
    - name: ObjectMeta.Labels
      kind: 24
      container: 21
    - name: ObjectMeta.Annotations
      kind: 24
      container: 21
    - name: ObjectMeta.Finalizers
      kind: 24
      container: 23
    - name: Spec.NetPeeringId
      kind: 24
    - name: DryRun
      kind: 24
      container: 23
    - name: FieldManager
      kind: 24
    - name: FieldValidation
      kind: 24
  Delete:
    use: Delete id
    flags:
    - name: GracePeriodSeconds
      kind: 6
    - name: Preconditions.UID
      kind: 24
    - name: Preconditions.ResourceVersion
      kind: 24
    - name: OrphanDependents
      kind: 1
    - name: PropagationPolicy
      kind: 24
    - name: DryRun
      kind: 24
      container: 23
  Get:
    use: Get id
    content: .
    entity: netpeering
    flags:
    - name: ResourceVersion
      kind: 24
  List:
    use: List
    content: Items
    entity: netpeering
    flags:
    - name: LabelSelector
      kind: 24
    - name: FieldSelector
      kind: 24
    - name: ResourceVersion
      kind: 24
    - name: ResourceVersionMatch
      kind: 24
    - name: TimeoutSeconds
      kind: 6
    - name: Limit
      kind: 6
    - name: ShardSelector
      kind: 24
  Update:
    use: Update
    content: Spec
    entity: netpeering
    flags:
    - name: ObjectMeta.Name
      kind: 24
    - name: ObjectMeta.GenerateName
      kind: 24
    - name: ObjectMeta.Namespace
      kind: 24
    - name: ObjectMeta.SelfLink
      kind: 24
    - name: ObjectMeta.UID
      kind: 24
    - name: ObjectMeta.ResourceVersion
      kind: 24
    - name: ObjectMeta.DeletionTimestamp
      kind: 24
      customValue: fileOrJson
    - name: ObjectMeta.DeletionGracePeriodSeconds
      kind: 6
    - name: ObjectMeta.Labels
      kind: 24
      container: 21
    - name: ObjectMeta.Annotations
      kind: 24
      container: 21
    - name: ObjectMeta.Finalizers
      kind: 24
      container: 23
    - name: Spec.NetPeeringId
      kind: 24
    - name: DryRun
      kind: 24
      container: 23
    - name: FieldManager
      kind: 24
    - name: FieldValidation
      kind: 24
entities:
  netpeering:
    title: Get
    columns:
    - title: Name
      content: .metadata.name
    - title: State
      content: .status.netPeeringState
    - title: Source Net
      content: .status.sourceNetId
    - title: Source Range
      content: .status.sourceIpRange
    - title: Source Account
      content: .status.sourceOwnerId
    - title: Accepter Net
      content: .status.accepterNetId
    - title: Accepter Range
      content: .status.accepterIpRange
    - title: Accepter Account
      content: .status.accepterOwnerId
    primary: Name
aliases:
- entity: netpeering
  use: list
  help: List netpeerings
  short: List netpeerings
  alias_to: List
  aliases:
  - ls
  alias_help: api List
  command:
  - netpeering
  - api
  - List
  - --output
  - table
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: netpeering
  use: describe id
  help: Describe a netpeering
  short: Describe a netpeering
  alias_to: Get
  aliases:
  - desc
  alias_help: Get id
  command:
  - netpeering
  - api
  - Get
  - '%0'
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: netpeering
  use: create
  help: Create a netpeering request
  short: Create a netpeering request
  alias_to: Create
  aliases:
  - add
  alias_help: request api Create
  command:
  - netpeering
  - request
  - api
  - Create
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
  - name: name
    alias_to: ObjectMeta.Name
    default: netpeering-request
  - name: accepter-net-id
    alias_to: Spec.AccepterNetId
  - name: accepter-owner-id
    alias_to: Spec.AccepterOwnerId
- entity: netpeering
  use: accept id
  help: Accept a netpeering request
  short: Accept a netpeering request
  alias_to: Create
  alias_help: acceptance api Create
  command:
  - netpeering
  - acceptance
  - api
  - Create
  - --Spec.NetPeeringId
  - '%0'
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
  - name: name
    alias_to: ObjectMeta.Name
    default: netpeering-acceptance
- entity: netpeering
  use: delete id [id]...
  help: Delete a NetPeering
  short: Delete a NetPeering
  alias_to: Delete
  aliases:
  - del
  - rm
  alias_help: Delete id
  command:
  - netpeering
  - api
  - Delete
  - '%0'
  - --output
  - success
  flags:
  - name: cluster
    alias_to: cluster
    required: true
