api:
  Create:
    use: Create
    content: .
    entity: nodepool
    flags:
    - name: ObjectMeta.Name
      kind: 24
    - name: ObjectMeta.GenerateName
      kind: 24
    - name: ObjectMeta.Namespace
      kind: 24
    - name: ObjectMeta.SelfLink
      kind: 24
    - name: ObjectMeta.UID
      kind: 24
    - name: ObjectMeta.ResourceVersion
      kind: 24
    - name: ObjectMeta.DeletionTimestamp
      kind: 24
      customValue: fileOrJson
    - name: ObjectMeta.DeletionGracePeriodSeconds
      kind: 6
    - name: ObjectMeta.Labels
      kind: 24
      container: 21
    - name: ObjectMeta.Annotations
      kind: 24
      container: 21
    - name: ObjectMeta.Finalizers
      kind: 24
      container: 23
    - name: Spec.AutoHealing
      kind: 1
    - name: Spec.Autoscaling
      kind: 1
    - name: Spec.DesiredNodes
      kind: 2
    - name: Spec.Fgpu.K8sOperator
      kind: 1
    - name: Spec.Fgpu.Model
      kind: 24
      values:
      - nvidia-a100
      - nvidia-a100-80
      - nvidia-h100
      - nvidia-l40
      - nvidia-m60
      - nvidia-p100
      - nvidia-p6
      - nvidia-v100
    - name: Spec.Flavour
      kind: 24
      values:
      - oks.debian12
      - oks.debian12_nvidia
      - oks.ubuntu22
    - name: Spec.Helms
      kind: 24
      container: 23
      values:
      - gpu-operator
      - ingress-nginx
      - ollama
      - prometheus
    - name: Spec.IpPoolName
      kind: 24
    - name: Spec.MaxNodes
      kind: 2
    - name: Spec.MinNodes
      kind: 2
    - name: Spec.NodeAnnotations
      kind: 24
      container: 21
    - name: Spec.NodeLabels
      kind: 24
      container: 21
    - name: Spec.NodeType
      kind: 24
    - name: Spec.PhysicalPlacement.NodeAttractCluster
      kind: 24
    - name: Spec.PhysicalPlacement.NodeAttractServer
      kind: 24
    - name: Spec.PhysicalPlacement.NodeRepulseCluster
      kind: 24
    - name: Spec.PhysicalPlacement.NodeRepulseServer
      kind: 24
    - name: Spec.Taint
      kind: 1
    - name: Spec.UpgradeStrategy.AutoUpgradeEnabled
      kind: 1
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.DurationHours
      kind: 2
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.Rrule
      kind: 24
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.StartHour
      kind: 2
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.WeekDay
      kind: 24
      values:
      - Fri
      - Mon
      - Sat
      - Sun
      - Thu
      - Tue
      - Wed
    - name: Spec.UpgradeStrategy.MaxSurge
      kind: 2
    - name: Spec.UpgradeStrategy.MaxUnavailable
      kind: 2
    - name: 'Spec.Volumes.#.Device'
      kind: 24
    - name: 'Spec.Volumes.#.Dir'
      kind: 24
    - name: 'Spec.Volumes.#.Iops'
      kind: 2
    - name: 'Spec.Volumes.#.Name'
      kind: 24
    - name: 'Spec.Volumes.#.Size'
      kind: 2
    - name: 'Spec.Volumes.#.Snapshot'
      kind: 24
    - name: 'Spec.Volumes.#.Type'
      kind: 24
      values:
      - gp2
      - io1
      - standard
    - name: Spec.Zones
      kind: 24
      container: 23
    - name: DryRun
      kind: 24
      container: 23
    - name: FieldManager
      kind: 24
    - name: FieldValidation
      kind: 24
  Delete:
    use: Delete id
    flags:
    - name: GracePeriodSeconds
      kind: 6
    - name: Preconditions.UID
      kind: 24
    - name: Preconditions.ResourceVersion
      kind: 24
    - name: OrphanDependents
      kind: 1
    - name: PropagationPolicy
      kind: 24
    - name: DryRun
      kind: 24
      container: 23
  Get:
    use: Get id
    content: .
    entity: nodepool
    flags:
    - name: ResourceVersion
      kind: 24
  List:
    use: List
    content: Items
    entity: nodepool
    flags:
    - name: LabelSelector
      kind: 24
    - name: FieldSelector
      kind: 24
    - name: ResourceVersion
      kind: 24
    - name: ResourceVersionMatch
      kind: 24
    - name: TimeoutSeconds
      kind: 6
    - name: Limit
      kind: 6
    - name: ShardSelector
      kind: 24
  Update:
    use: Update
    content: Spec
    entity: nodepool
    flags:
    - name: ObjectMeta.Name
      kind: 24
    - name: ObjectMeta.GenerateName
      kind: 24
    - name: ObjectMeta.Namespace
      kind: 24
    - name: ObjectMeta.SelfLink
      kind: 24
    - name: ObjectMeta.UID
      kind: 24
    - name: ObjectMeta.ResourceVersion
      kind: 24
    - name: ObjectMeta.DeletionTimestamp
      kind: 24
      customValue: fileOrJson
    - name: ObjectMeta.DeletionGracePeriodSeconds
      kind: 6
    - name: ObjectMeta.Labels
      kind: 24
      container: 21
    - name: ObjectMeta.Annotations
      kind: 24
      container: 21
    - name: ObjectMeta.Finalizers
      kind: 24
      container: 23
    - name: Spec.AutoHealing
      kind: 1
    - name: Spec.Autoscaling
      kind: 1
    - name: Spec.DesiredNodes
      kind: 2
    - name: Spec.Fgpu.K8sOperator
      kind: 1
    - name: Spec.Fgpu.Model
      kind: 24
      values:
      - nvidia-a100
      - nvidia-a100-80
      - nvidia-h100
      - nvidia-l40
      - nvidia-m60
      - nvidia-p100
      - nvidia-p6
      - nvidia-v100
    - name: Spec.Flavour
      kind: 24
      values:
      - oks.debian12
      - oks.debian12_nvidia
      - oks.ubuntu22
    - name: Spec.Helms
      kind: 24
      container: 23
      values:
      - gpu-operator
      - ingress-nginx
      - ollama
      - prometheus
    - name: Spec.IpPoolName
      kind: 24
    - name: Spec.MaxNodes
      kind: 2
    - name: Spec.MinNodes
      kind: 2
    - name: Spec.NodeAnnotations
      kind: 24
      container: 21
    - name: Spec.NodeLabels
      kind: 24
      container: 21
    - name: Spec.NodeType
      kind: 24
    - name: Spec.PhysicalPlacement.NodeAttractCluster
      kind: 24
    - name: Spec.PhysicalPlacement.NodeAttractServer
      kind: 24
    - name: Spec.PhysicalPlacement.NodeRepulseCluster
      kind: 24
    - name: Spec.PhysicalPlacement.NodeRepulseServer
      kind: 24
    - name: Spec.Taint
      kind: 1
    - name: Spec.UpgradeStrategy.AutoUpgradeEnabled
      kind: 1
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.DurationHours
      kind: 2
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.Rrule
      kind: 24
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.StartHour
      kind: 2
    - name: Spec.UpgradeStrategy.AutoUpgradeMaintenance.WeekDay
      kind: 24
      values:
      - Fri
      - Mon
      - Sat
      - Sun
      - Thu
      - Tue
      - Wed
    - name: Spec.UpgradeStrategy.MaxSurge
      kind: 2
    - name: Spec.UpgradeStrategy.MaxUnavailable
      kind: 2
    - name: 'Spec.Volumes.#.Device'
      kind: 24
    - name: 'Spec.Volumes.#.Dir'
      kind: 24
    - name: 'Spec.Volumes.#.Iops'
      kind: 2
    - name: 'Spec.Volumes.#.Name'
      kind: 24
    - name: 'Spec.Volumes.#.Size'
      kind: 2
    - name: 'Spec.Volumes.#.Snapshot'
      kind: 24
    - name: 'Spec.Volumes.#.Type'
      kind: 24
      values:
      - gp2
      - io1
      - standard
    - name: Spec.Zones
      kind: 24
      container: 23
    - name: DryRun
      kind: 24
      container: 23
    - name: FieldManager
      kind: 24
    - name: FieldValidation
      kind: 24
entities:
  nodepool:
    title: Get
    columns:
    - title: Name
      content: .metadata.name
    - title: NodeType
      content: .spec.nodeType
    - title: Min nodes
      content: .spec.minNodes
    - title: Max nodes
      content: .spec.maxNodes
    - title: Desired
      content: .spec.desiredNodes
    - title: Attached
      content: .status.progress.attached
    - title: Ready
      content: .status.progress.ready
    - title: Running
      content: .status.progress.running
    - title: Pending
      content: .status.progress.pending
    - title: Stopping
      content: .status.progress.stopping
    - title: Stopped
      content: .status.progress.stopped
    - title: Shutting down
      content: .status.progress.shutting_down
    - title: Processing state
      content: .status.state.name
    - title: Last error
      content: .status.last_error.message
    primary: Name
aliases:
- entity: nodepool
  use: list
  alias_to: List
  aliases:
  - ls
  alias_help: List
  command:
  - nodepool
  - api
  - List
  - --output
  - table
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: nodepool
  use: describe id [id]...
  help: Describe a nodepool
  short: Describe a nodepool
  alias_to: Get
  aliases:
  - desc
  alias_help: Get id
  command:
  - nodepool
  - api
  - Get
  - '%0'
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: nodepool
  use: create
  help: Create a nodepool
  short: Create a nodepool
  alias_to: Create
  aliases:
  - add
  alias_help: Create
  command:
  - api
  - GetNodepoolTemplate
  - --jq
  - .Template | .spec.desiredNodes=0
  - --single
  - '|'
  - nodepool
  - api
  - Create
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
  - name: name
    alias_to: ObjectMeta.Name
    required: true
  - name: auto-healing
    alias_to: Spec.AutoHealing
  - name: autoscaling
    alias_to: Spec.Autoscaling
  - name: desired-nodes
    alias_to: Spec.DesiredNodes
    required: true
  - name: fgpu-operator
    alias_to: Spec.Fgpu.K8sOperator
  - name: fgpu-model
    alias_to: Spec.Fgpu.Model
  - name: flavour
    alias_to: Spec.Flavour
  - name: helms
    alias_to: Spec.Helms
  - name: ip-pool
    alias_to: Spec.IpPoolName
  - name: max-nodes
    alias_to: Spec.MaxNodes
  - name: min-nodes
    alias_to: Spec.MinNodes
  - name: node-type
    alias_to: Spec.NodeType
    required: true
  - name: node-annotations
    alias_to: Spec.NodeAnnotations
  - name: node-labels
    alias_to: Spec.NodeLabels
  - name: placement-attract-cluster
    alias_to: Spec.PhysicalPlacement.NodeAttractCluster
  - name: placement-attract-server
    alias_to: Spec.PhysicalPlacement.NodeAttractServer
  - name: placement-repulse-cluster
    alias_to: Spec.PhysicalPlacement.NodeRepulseCluster
  - name: placement-repulse-server
    alias_to: Spec.PhysicalPlacement.NodeRepulseServer
  - name: taint
    alias_to: Spec.Taint
  - name: auto-upgrade-enabled
    alias_to: Spec.UpgradeStrategy.AutoUpgradeEnabled
  - name: upgrade-duration-hour
    alias_to: Spec.UpgradeStrategy.AutoUpgradeMaintenance.DurationHours
  - name: upgrade-rrule
    alias_to: Spec.UpgradeStrategy.AutoUpgradeMaintenance.Rrule
  - name: upgrade-start-hour
    alias_to: Spec.UpgradeStrategy.AutoUpgradeMaintenance.StartHour
  - name: upgrade-week-day
    alias_to: Spec.UpgradeStrategy.AutoUpgradeMaintenance.WeekDay
  - name: upgrade-max-surge
    alias_to: Spec.UpgradeStrategy.MaxSurge
  - name: upgrade-max-unavailable
    alias_to: Spec.UpgradeStrategy.MaxUnavailable
  - name: volume-iops
    alias_to: Spec.Volumes.0.Iops
  - name: volume-size
    alias_to: Spec.Volumes.0.Size
  - name: volume-snapshot
    alias_to: Spec.Volumes.0.Snapshot
  - name: volume-type
    alias_to: Spec.Volumes.0.Type
  - name: zones
    alias_to: Spec.Zones
    required: true
- entity: nodepool
  use: delete id [id]...
  help: Delete a nodepool
  short: Delete a nodepool
  alias_to: Delete
  aliases:
  - del
  - rm
  alias_help: Delete id
  command:
  - nodepool
  - api
  - Delete
  - '%0'
  - --output
  - success
  flags:
  - name: cluster
    alias_to: cluster
    required: true
