api:
  Create:
    use: Create
    content: .
    entity: ippool
    flags:
    - name: ObjectMeta.Name
      kind: 24
    - name: ObjectMeta.GenerateName
      kind: 24
    - name: ObjectMeta.Namespace
      kind: 24
    - name: ObjectMeta.SelfLink
      kind: 24
    - name: ObjectMeta.UID
      kind: 24
    - name: ObjectMeta.ResourceVersion
      kind: 24
    - name: ObjectMeta.DeletionTimestamp
      kind: 24
      customValue: fileOrJson
    - name: ObjectMeta.DeletionGracePeriodSeconds
      kind: 6
    - name: ObjectMeta.Labels
      kind: 24
      container: 21
    - name: ObjectMeta.Annotations
      kind: 24
      container: 21
    - name: ObjectMeta.Finalizers
      kind: 24
      container: 23
    - name: Spec.NumAddresses
      kind: 2
    - name: Spec.Persistent
      kind: 1
    - name: DryRun
      kind: 24
      container: 23
    - name: FieldManager
      kind: 24
    - name: FieldValidation
      kind: 24
  Delete:
    use: Delete id
    flags:
    - name: GracePeriodSeconds
      kind: 6
    - name: Preconditions.UID
      kind: 24
    - name: Preconditions.ResourceVersion
      kind: 24
    - name: OrphanDependents
      kind: 1
    - name: PropagationPolicy
      kind: 24
    - name: DryRun
      kind: 24
      container: 23
  Get:
    use: Get id
    content: .
    entity: ippool
    flags:
    - name: ResourceVersion
      kind: 24
  List:
    use: List
    content: Items
    entity: ippool
    flags:
    - name: LabelSelector
      kind: 24
    - name: FieldSelector
      kind: 24
    - name: ResourceVersion
      kind: 24
    - name: ResourceVersionMatch
      kind: 24
    - name: TimeoutSeconds
      kind: 6
    - name: Limit
      kind: 6
    - name: ShardSelector
      kind: 24
  Update:
    use: Update
    content: Spec
    entity: ippool
    flags:
    - name: ObjectMeta.Name
      kind: 24
    - name: ObjectMeta.GenerateName
      kind: 24
    - name: ObjectMeta.Namespace
      kind: 24
    - name: ObjectMeta.SelfLink
      kind: 24
    - name: ObjectMeta.UID
      kind: 24
    - name: ObjectMeta.ResourceVersion
      kind: 24
    - name: ObjectMeta.DeletionTimestamp
      kind: 24
      customValue: fileOrJson
    - name: ObjectMeta.DeletionGracePeriodSeconds
      kind: 6
    - name: ObjectMeta.Labels
      kind: 24
      container: 21
    - name: ObjectMeta.Annotations
      kind: 24
      container: 21
    - name: ObjectMeta.Finalizers
      kind: 24
      container: 23
    - name: Spec.NumAddresses
      kind: 2
    - name: Spec.Persistent
      kind: 1
    - name: DryRun
      kind: 24
      container: 23
    - name: FieldManager
      kind: 24
    - name: FieldValidation
      kind: 24
entities:
  ippool:
    title: Get
    columns:
    - title: Name
      content: .metadata.name
    - title: Allocated
      content: .status.progress.allocatedAddresses
    - title: Linked
      content: .status.progress.linkedAddresses
    - title: Unlinked
      content: .status.progress.unlinkedAddresses
    primary: Name
aliases:
- entity: ippool
  use: list
  help: List ippools
  short: List ippools
  alias_to: List
  aliases:
  - ls
  alias_help: List
  command:
  - ippool
  - api
  - List
  - --output
  - table
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: ippool
  use: describe id
  help: Describe an ippool
  short: Describe an ippool
  alias_to: Get
  aliases:
  - desc
  alias_help: Get id
  command:
  - ippool
  - api
  - Get
  - '%0'
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: ippool
  use: delete id [id]...
  help: Delete an ippool
  short: Delete an ippool
  alias_to: Delete
  aliases:
  - del
  - rm
  alias_help: Delete id
  command:
  - ippool
  - api
  - Delete
  - '%0'
  - --output
  - success
  flags:
  - name: cluster
    alias_to: cluster
    required: true
- entity: ippool
  use: create
  help: Create an ippool
  short: Create an ippool
  alias_to: Create
  aliases:
  - add
  command:
  - ippool
  - api
  - Create
  - --output
  - yaml
  - --single
  flags:
  - name: cluster
    alias_to: cluster
    required: true
  - name: name
    alias_to: ObjectMeta.Name
    required: true
  - name: num-addresses
    alias_to: Spec.NumAddresses
    required: true
